//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadPatterns
{
    using System;
    using System.Collections.Generic;
    
    public partial class Design
    {
        public int DesignID { get; set; }
        public int AlbumID { get; set; }
        public string Caption { get; set; }
        public string Description { get; set; }
        public int NDownloaded { get; set; }
        public string Notes { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int NColors { get; set; }
        public string Text { get; set; }
        public Nullable<int> NSubscriptions { get; set; }
        public Nullable<int> NPage { get; set; }
    
        public virtual Album Album { get; set; }
    }
}
